#
#  setup packaging - Mon Feb  2 16:56:34 EST 2015
#
execute_process(COMMAND uname -m OUTPUT_VARIABLE ARCH)

set(CPACK_PACKAGE_VERSION ${VERSION})
set(CPACK_GENERATOR "RPM;DEB")
set(CPACK_PACKAGE_RELEASE 1)
set(CPACK_PACKAGE_CONTACT "Greg Eisenhauer")
set(CPACK_PACKAGE_VENDOR "CERCS")
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "${ARCH}")
include(CPack)
